import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync, spawn, execFile} from 'node:child_process';
import {promisify} from 'node:util';
const exec=promisify(execFile);
const inputRun=(file,args,options,input)=>new Promise((resolve,reject)=>{const child=spawn(file,args,options);let out='',err='';child.stdout.on('data',c=>out+=c);child.stderr.on('data',c=>err+=c);child.on('error',reject);child.on('close',code=>code?reject(new Error(err+'\n'+out)):resolve(out));child.stdin.end(input);});
import {createServer} from 'node:http';
import {build} from 'esbuild';
import pg from 'pg';

test('compiled original tick -> real cloud PostgreSQL discovery/selection/history/stop, private wire',async t=>{
 const root=process.cwd(),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'node-git-core-'));
 const container=execFileSync('docker',['run','-d','--rm','-e','POSTGRES_PASSWORD=test','-e','POSTGRES_DB=test','-P','postgres:16-alpine'],{encoding:'utf8'}).trim();
 let pool,server;
 t.after(async()=>{if(server?.listening)await new Promise(r=>server.close(r));await pool?.end();execFileSync('docker',['rm','-f',container],{stdio:'ignore'});fs.rmSync(tmp,{recursive:true,force:true});});
 const port=execFileSync('docker',['port',container,'5432/tcp'],{encoding:'utf8'}).trim().split('\n')[0].split(':').pop();
 pool=new pg.Pool({host:'127.0.0.1',port:Number(port),user:'postgres',password:'test',database:'test'});
 for(let n=0;;n++){try{await pool.query('select 1');break;}catch(e){if(n>80)throw e;await new Promise(r=>setTimeout(r,100));}}
 await pool.query(`create table companies(id bigint primary key);create table app_users(id bigint primary key,company_id bigint,email text,approval_status text);
 insert into companies values(1);insert into app_users values(11,1,'test@example.test','approved');
 create table files_agent_devices(id bigserial primary key,company_id bigint,user_id bigint,enrollment_id bigint not null,credential_hash text unique,device_label text,platform text,revoked_at timestamptz,last_seen_at timestamptz);
 create table projects(id bigint primary key,client_id bigint,approval_status text,git_repository_key text,status text,tracemini_telemetry_paused boolean default false,tracemini_resume_epoch int default 0);
 create table project_memberships(project_id bigint,user_id bigint,membership_status text);
 create table project_tracemini_roots(id bigserial primary key,project_id bigint,device_id bigint,binding_id text,binding_secret_hash text,root_hash text,root_label text,repository_key text,status text,approved_by bigint,approved_at timestamptz,last_heartbeat_at timestamptz,revoked_at timestamptz,unique(project_id,device_id,root_hash));
 create table tracemini_runtime_settings(singleton boolean,tracemini_global_pause boolean,tracemini_embedded_enabled boolean);insert into tracemini_runtime_settings values(true,false,true);
 create table project_tracemini_events(id bigserial primary key,project_id bigint,device_id bigint,root_id bigint,event_key text,kind text,action text,repository_key text,occurred_at timestamptz,provenance jsonb,evidence_eligible boolean,resume_epoch int,unique(root_id,event_key));
 insert into projects(id,client_id,approval_status,git_repository_key,status) values(700,11,'approved','github.com/acme/widget','completed');`);
 for(const name of ['020_tracemini_project_discovery.sql','021_tracemini_node_install.sql','022_tracemini_node_git.sql'])await pool.query(fs.readFileSync('migrations/'+name,'utf8'));
 const token='etn_'+crypto.randomBytes(32).toString('base64url');
 await pool.query(`insert into tracemini_node_contexts(id,company_id,user_id) values(50,1,11)`);
 await pool.query(`insert into tracemini_node_devices(id,context_id,company_id,user_id,installation_hash,credential_hash,machine_name) values(5,50,1,11,$1,$2,'test')`,['a'.repeat(64),crypto.createHash('sha256').update(token).digest('hex')]);
 globalThis.__nodeGitPool=pool;process.env.FILES_AGENT_BINDING_KEY='test-only-binding-secret'.repeat(3);
 const outfile=path.join(root,'build/tracemini/node-git-test-server.mjs');
 await build({stdin:{contents:"export * from './lib/tracemini-node-git';export * from './lib/tracemini-discovery';export * from './lib/tracemini-install';",resolveDir:root},bundle:true,platform:'node',format:'esm',packages:'external',outfile,plugins:[{name:'db-only-fixture',setup(b){b.onResolve({filter:/^server-only$/},()=>({path:'empty',namespace:'fixture'}));b.onResolve({filter:/^\.\/db$/},()=>({path:'db',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},a=>({contents:a.path==='db'?'export const getPool=()=>globalThis.__nodeGitPool;export const ensureSchema=async()=>{};':''}));}}]});
 const cloud=await import('file://'+outfile+'?t='+Date.now()), wire=[];
 let offlinePush=false;
 server=createServer(async(req,res)=>{if(offlinePush&&req.url.endsWith('/push')){res.writeHead(503).end('{}');return;}let body='';for await(const c of req)body+=c;wire.push({url:req.url,body});try{const auth=(req.headers.authorization||'').replace(/^Bearer /,'');const data=JSON.parse(body||'{}');const result=req.url.endsWith('/exchange')?await cloud.exchangeNodeInstallation(data,auth):req.url.endsWith('/status')?await cloud.nodeDeviceStatus(auth):await cloud.nodeGitRequest(auth,req.url.split('/').pop(),data);res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify(result));}catch(e){res.writeHead(e.status||500).end(JSON.stringify({error:e.code||e.message}));}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const origin='http://127.0.0.1:'+server.address().port;
 const repo=path.join(tmp,'private-folder','widget');fs.mkdirSync(repo,{recursive:true});
 const git=(...args)=>execFileSync('git',['-C',repo,...args],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
 git('init','-b','main');git('config','user.name','Private Name');git('config','user.email','private@example.test');
 fs.writeFileSync(path.join(repo,'secret-source.txt'),'not uploaded');git('add','.');git('commit','-m','PRIVATE-COMMIT-MESSAGE');
 git('remote','add','origin','https://secret-user:SECRET-PASSWORD@github.com/acme/widget.git?token=SECRET-QUERY');
 process.env.EMPLOYEE_TRACE_HOME=path.join(tmp,'state');
 const engine=await import('file://'+root+'/build/tracemini/engine.mjs?test='+Date.now());
 const config={...engine.loadConfig(),serverUrl:origin,agentToken:token,agentId:5,workspaceId:50,watchedPaths:[path.join(tmp,'private-folder')],clones:[]};engine.saveConfig(config);
 await engine.tick(config);const session={id:'11',company_id:'1',email:'test@example.test'};
 const scan=await cloud.createNodeRepositoryScan(session,5);await engine.tick(config);
 assert.equal((await cloud.repositoryScanStatus(session,scan.requestId)).state,'completed');
 let candidate=(await cloud.listRepositoryCandidates(session))[0];assert.equal(candidate.matched_project_id,'700');assert.equal(candidate.repository_key,'github.com/acme/widget');assert.equal(candidate.match_status,'matched');
 assert.deepEqual(Object.keys((await pool.query('select fingerprint from tracemini_repository_candidates')).rows[0].fingerprint),['digest']);
 await cloud.selectRepositoryCandidate(session,candidate.id,true,candidate.revision);await engine.tick(config);
 candidate=(await cloud.listRepositoryCandidates(session))[0];assert.equal(candidate.tracking_state,'tracking');
 assert.equal(engine.loadConfig().clones.length,1);assert.equal(engine.loadConfig().clones[0].workspaceId,700);assert.equal(engine.loadConfig().workspaceId,50);
 assert.match(fs.readFileSync(path.join(repo,'.git/hooks/post-commit'),'utf8'),/Employee Trace/);
 let events=(await pool.query('select * from project_tracemini_events')).rows;assert.equal(events.length,1);assert.equal(events[0].project_id,'700');assert.equal(events[0].action,'commit_history');assert.equal(events[0].evidence_eligible,false);
 // Incremental recovery runs actual original commitHistoryAfterHeads, not a mock.
 fs.writeFileSync(path.join(repo,'secret-source.txt'),'second');git('-c','core.hooksPath=/dev/null','add','.');git('-c','core.hooksPath=/dev/null','commit','-m','SECOND-PRIVATE-MESSAGE');await engine.tick(config);await engine.tick(config);
 events=(await pool.query('select * from project_tracemini_events')).rows;assert.equal(events.length,2);
 const recorded=JSON.stringify(wire);for(const secret of [repo,tmp,'SECRET-PASSWORD','SECRET-QUERY','secret-user','Private Name','private@example.test','PRIVATE-COMMIT-MESSAGE','secret-source.txt'])assert.ok(!recorded.includes(secret),'wire leaked '+secret);
 assert.equal((await pool.query('select count(*)::int as n from projects')).rows[0].n,1);
 // Replay and forged project IDs cannot register or ingest into other projects.
 const register=wire.find(w=>w.url.endsWith('/register'));const registration=JSON.parse(register.body);
 await assert.rejects(cloud.nodeGitRequest(token,'register',{...registration,project_id:701}));
 await assert.rejects(cloud.claimDeviceWork(token),e=>e.status===401);
 await assert.rejects(cloud.nodeGitRequest('fad_python','sync',{}),e=>e.status===401);
 // Actual original installer, same-device exchange, guided roots, fake systemctl only.
 const bin=path.join(tmp,'bin');fs.mkdirSync(bin);fs.writeFileSync(path.join(bin,'systemctl'),'#!/bin/sh\nprintf "%s\\n" "$*" >> "$HOME/systemctl.log"\n');fs.chmodSync(path.join(bin,'systemctl'),0o755);
 const env={...process.env,HOME:tmp,PATH:bin+':'+path.join(tmp,'.local/bin')+':'+process.env.PATH,EMPLOYEE_TRACE_PUSH_CONFIRM_DELAY_MS:'1000'};
 const machine=fs.readFileSync('/etc/machine-id','utf8').trim()||os.hostname();const installationId=crypto.createHash('sha256').update(`employee-trace-installation-v1\0${origin}\0${process.getuid()}\0${machine}`).digest('hex');
 await pool.query('update tracemini_node_devices set installation_hash=$1 where id=5',[crypto.createHash('sha256').update(installationId).digest('hex')]);
 const minted=await cloud.mintNodeInstallation(session);const {linuxInstaller}=await import('../build/tracemini/installer.mjs');
 const script=path.join(tmp,'install.sh');fs.writeFileSync(script,linuxInstaller(path.join(root,'build/tracemini/cli'),origin,minted.token));
 const output=await inputRun('sh',[script],{env},repo+'\nn\n');assert.match(output,/Paste a folder location/);assert.match(output,/Background service started/);
 assert.match(fs.readFileSync(path.join(tmp,'.config/systemd/user/employee-trace.service'),'utf8'),/ start/);assert.match(fs.readFileSync(path.join(tmp,'systemctl.log'),'utf8'),/is-active/);
 assert.equal(engine.loadConfig().clones.length,1);assert.equal(engine.loadConfig().workspaceId,50);assert.equal(engine.loadConfig().agentToken,token);
 const cli=path.join(tmp,'.local/bin/employee-trace');const status=JSON.parse((await exec(cli,['status'],{env})).stdout);assert.equal(status.service,'active');await exec(cli,['use-workspace','700'],{env});assert.equal(engine.loadConfig().workspaceId,50);await assert.rejects(exec(cli,['use-workspace','701'],{env}));
 const synced=await cloud.mintNodeInstallation(session);await exec(cli,['sync','--server',origin,'--install-token',synced.token],{env});assert.equal(engine.loadConfig().clones.length,1);
 await cloud.selectRepositoryCandidate(session,candidate.id,false,candidate.revision);await engine.tick(config);
 assert.equal(engine.loadConfig().clones.length,0);assert.equal((await cloud.listRepositoryCandidates(session))[0].tracking_state,'stopped');assert.equal(fs.existsSync(path.join(repo,'.git/hooks/post-commit')),false);
 const event=JSON.parse(wire.find(w=>w.url.endsWith('/activity')).body);await assert.rejects(cloud.nodeGitRequest(token,'activity',event));
 // Real bare remote + real installed pre-push hook, with durable offline retry.
 const bare=path.join(tmp,'remote.git'),local=path.join(tmp,'push-repo');execFileSync('git',['init','--bare',bare],{stdio:'ignore'});fs.mkdirSync(local);
 const g=(...a)=>execFileSync('git',['-C',local,...a],{encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim();
 g('init','-b','main');g('config','user.name','Fixture');g('config','user.email','fixture@example.test');fs.writeFileSync(path.join(local,'private.txt'),'private');g('add','.');g('commit','-m','private');g('remote','add','origin',bare);
 await exec(cli,['watch',local],{env});let pc=(await cloud.listRepositoryCandidates(session)).find(c=>c.repository_key.startsWith('local:'));assert.ok(pc);
 await pool.query("insert into projects(id,client_id,approval_status,git_repository_key,status) values(701,11,'approved',$1,'completed')",[pc.repository_key]);
 await exec(cli,['watch',local],{env});pc=(await cloud.listRepositoryCandidates(session)).find(c=>c.id===pc.id);await cloud.selectRepositoryCandidate(session,pc.id,true,pc.revision);await exec(cli,['once'],{env});
 offlinePush=true;await exec('git',['-C',local,'push','origin','main'],{env});
 const queuePath=path.join(process.env.EMPLOYEE_TRACE_HOME,'queue.json');
 assert.ok(JSON.parse(fs.readFileSync(queuePath,'utf8')).some(e=>e.type==='push'),'pre-push intent survives offline in original durable queue');
 await exec(cli,['once'],{env});assert.equal((await pool.query('select count(*)::int n from tracemini_pending_pushes')).rows[0].n,0);
 offlinePush=false;const queue=JSON.parse(fs.readFileSync(queuePath,'utf8'));for(const e of queue)e.nextAttempt=0;fs.writeFileSync(queuePath,JSON.stringify(queue));
 await exec(cli,['once'],{env});
 const pending=(await pool.query('select * from tracemini_pending_pushes')).rows[0];assert.equal(pending.status,'pending');
 assert.equal((await pool.query("select count(*)::int n from project_tracemini_events where kind='push'")).rows[0].n,0,'intent alone is not verified push evidence');
 await new Promise(r=>setTimeout(r,Math.max(0,new Date(pending.created_at).getTime()+1100-Date.now())));
 await exec(cli,['once'],{env});
 const push=(await pool.query('select * from tracemini_pending_pushes')).rows[0];assert.equal(push.status,'verified');assert.equal(push.branch,'refs/heads/main');assert.equal(push.expected_head_sha,g('rev-parse','HEAD'));
 const pushEvent=(await pool.query("select * from project_tracemini_events where kind='push'")).rows[0];assert.equal(pushEvent.action,'git_push');assert.equal(pushEvent.evidence_eligible,false);assert.equal(pushEvent.provenance.remote_head_sha,push.expected_head_sha);
 const pushWire=wire.filter(w=>w.url.endsWith('/push'));const intent=JSON.parse(pushWire[0].body);await cloud.nodeGitRequest(token,'push',intent);assert.equal((await pool.query('select count(*)::int n from tracemini_pending_pushes')).rows[0].n,1);
 const complete=JSON.parse(wire.find(w=>w.url.endsWith('/complete')&&JSON.parse(w.body).kind==='push').body);await assert.rejects(cloud.nodeGitRequest(token,'complete',{...complete,claim_token:'forged'}));
 assert.ok(!JSON.stringify(pushWire).includes(bare));assert.ok(!JSON.stringify(pushWire).includes(local));
 await pool.query('update tracemini_node_devices set revoked_at=now() where id=5');await assert.rejects(engine.tick(config));
});
